[test-groups]
serial-integration = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'test(test_stop_taker_after_setup)'
test-group = "serial-integration"

[[profile.default.overrides]]
filter = 'test(test_abort_case_2_move_on_with_other_makers)'
test-group = "serial-integration"

[[profile.default.overrides]]
filter = 'test(test_abort_case_2_recover_if_no_makers_found)'
test-group = "serial-integration"

[[profile.default.overrides]]
filter = 'test(maker_drops_after_sending_senders_sigs)'
test-group = "serial-integration"

[[profile.default.overrides]]
filter = 'test(abort3_case1_close_at_contract_sigs_for_recvr_and_sender)'
test-group = "serial-integration"

[[profile.default.overrides]]
filter = 'test(abort3_case2_close_at_contract_sigs_for_recvr)'
test-group = "serial-integration"

[[profile.default.overrides]]
filter = 'test(abort3_case3_close_at_hash_preimage_handover)'
test-group = "serial-integration"

[[profile.default.overrides]]
filter = 'test(test_fidelity_complete)'
test-group = "serial-integration"

[[profile.default.overrides]]
filter = 'test(test_create_funding_txn_with_varied_distributions)'
test-group = "serial-integration"

[[profile.default.overrides]]
filter = 'test(malice1_taker_broadcast_contract_prematurely)'
test-group = "serial-integration"

[[profile.default.overrides]]
filter = 'test(malice2_maker_broadcast_contract_prematurely)'
test-group = "serial-integration"

[[profile.default.overrides]]
filter = 'test(multi_taker_single_maker_swap)'
test-group = "serial-integration"

[[profile.default.overrides]]
filter = 'test(test_standard_coinswap)'
test-group = "serial-integration"

[[profile.default.overrides]]
filter = 'test(test_taker_cli)'
test-group = "serial-integration"

[[profile.default.overrides]]
filter = 'test(test_taproot_coinswap)'
test-group = "serial-integration"

[[profile.default.overrides]]
filter = 'test(run_all_utxo_tests)'
test-group = "serial-integration"

[[profile.default.overrides]]
filter = 'test(encwallet_encbackup_encrestore)'
test-group = "serial-integration"

[[profile.default.overrides]]
filter = 'test(plainwallet_plainbackup_plainrestore)'
test-group = "serial-integration"
